languages:
  JavaScript: true
engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        - javascript
ratings:
  paths:
  - src/**/*.jsx
  - src/**/*.js
  - src/**/*.pcss
exclude_paths:
- coverage/**/*
- docs/**/*
- public/**/*
- flow-typed/**/*
- implements/**/*
- styleguide/**/*
- src/**/*.spec.jsx
- src/**/*.spec.js
- src/components/__exampless__/**/*
