language: node_js
node_js:
  - 4
  - 6
  - 7
cache: yarn
script:
  # Run tests
  - |
    yarn run lint
    echo "TRAVIS_NODE_VERSION=$TRAVIS_NODE_VERSION"
    if [[ "$TRAVIS_NODE_VERSION" =~ ^(4|5)$ ]]; then
      NODE_ENV=test node --harmony-proxies $(npm bin)/jest src -c ./implements/jest.config.json --coverage --verbose --runInBand
    else
      yarn run test:coverage -- --runInBand
    fi
  # Build 
  - yarn run build
after_success:
  # Upload coverage report to Codecov
  - bash <(curl -s https://codecov.io/bash)