language: node_js
node_js:
  - 4
  - 6
  - 7
cache: yarn
script:
  # Run tests in all commits
  - |
    echo "TRAVIS_NODE_VERSION=$TRAVIS_NODE_VERSION"
    if [[ "$TRAVIS_NODE_VERSION" =~ ^(4|5)$ ]]; then
      NODE_ENV=test node --harmony-proxies $(npm bin)/jest src -c ./implements/jest.config.json --coverage --verbose --runInBand
    else
      yarn run test:coverage -- --runInBand
    fi

  # Build in all commits
  - yarn run createApp
  - yarn run styleguide:build

  # Linting if PR
  - |
    echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
    echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
    if [[ "$TRAVIS_PULL_REQUEST" ]]; then
      yarn run eslint
    fi
  - |
    if [[ "$TRAVIS_PULL_REQUEST" ]]; then
      yarn run stylelint
    fi
  - |
    if [[ "$TRAVIS_PULL_REQUEST" ]]; then
      yarn run flow
    fi

after_success:
  # Upload coverage report to Codecov
  - bash <(curl -s https://codecov.io/bash)
